const QUIZ_QUESTIONS = [
    {
        q: "QUAL E IL SEGNALE DI SOCCORSO INTERNAZIONALE?",
        a: ["SOS", "CQD", "MAYDAY", "QRR"],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA IL CODICE Q QTH?",
        a: ["LA MIA POSIZIONE E", "IL MIO NOME E", "SONO PRONTO", "CHIUDO LA STAZIONE"],
        correct: 0
    },
    {
        q: "QUALE ABBREVIAZIONE SI USA PER BUONGIORNO?",
        a: ["GM", "GA", "GN", "GE"],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA IL CODICE Q QRS?",
        a: ["TRASMETTETE PIU PIANO", "AUMENTATE LA VELOCITA", "IL SEGNALE E FORTE", "CAMBIO FREQUENZA"],
        correct: 0
    },
    {
        q: "QUAL E L ABBREVIAZIONE DI BEST REGARDS?",
        a: ["73", "88", "DX", "GL"],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA IL CODICE Q QRV?",
        a: ["SONO PRONTO", "SONO OCCUPATO", "VADO FUORI ONDA", "RIPETETE IL MESSAGGIO"],
        correct: 0
    },
    {
        q: "QUALE CARATTERE MORSE CORRISPONDE ALLA LETTERA E?",
        a: [".", "-", "..", ".-"],
        correct: 0
    },
    {
        q: "QUALE CARATTERE MORSE CORRISPONDE ALLA LETTERA T?",
        a: ["-", ".", "--", "-."],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA L ABBREVIAZIONE OM?",
        a: ["OLD MAN", "OPERATOR MODE", "ONLY MORSE", "OFFICIAL MEMBER"],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA IL CODICE Q QSL?",
        a: ["CONFERMO LA RICEZIONE", "NON RICEVO BENE", "LA MIA FREQUENZA E", "SPOSTATEVI"],
        correct: 0
    },
    // --- ELETTROTECNICA ---
    {
        q: "QUALE FORMULA ESPRIME LA PRIMA LEGGE DI OHM?",
        a: ["V = R * I", "P = V * I", "R = V * P", "I = R / V"],
        correct: 0
    },
    {
        q: "QUAL E L UNITA DI MISURA DELLA FREQUENZA?",
        a: ["HERTZ", "WATT", "OHM", "AMPERE"],
        correct: 0
    },
    {
        q: "COSA MISURA IL WATT?",
        a: ["POTENZA", "TENSIONE", "RESISTENZA", "CORRENTE"],
        correct: 0
    },
    {
        q: "QUALE COMPONENTE ACCUMULA ENERGIA IN UN CAMPO ELETTRICO?",
        a: ["CONDENSATORE", "INDUTTORE", "RESISTORE", "DIODO"],
        correct: 0
    },
    {
        q: "COSA SUCCEDE SE DUE RESISTENZE UGUALI SONO IN PARALLELO?",
        a: ["LA RESISTENZA DIMEZZA", "LA RESISTENZA RADDOPPIA", "LA TENSIONE SI SOMMA", "NON SUCCEDE NULLA"],
        correct: 0
    },
    {
        q: "QUAL E L UNITA DI MISURA DELLA CAPACITA?",
        a: ["FARAD", "HENRY", "VOLT", "TESLA"],
        correct: 0
    },
    {
        q: "QUALE COMPONENTE PERMETTE IL PASSAGGIO DI CORRENTE IN UN SOLO VERSO?",
        a: ["DIODO", "TRANSISTOR", "RELE", "FUSIBILE"],
        correct: 0
    },
    {
        q: "COSA MISURA UN TESTER IMPOSTATO SU OHM?",
        a: ["RESISTENZA", "TENSIONE ALTERNATA", "CAPACITA", "GUADAGNO"],
        correct: 0
    },
    {
        q: "QUAL E IL SIMBOLO CHIMICO DEL PIOMBO NELLE BATTERIE?",
        a: ["PB", "CU", "AG", "AU"],
        correct: 0
    },
    {
        q: "A QUANTI MILLIAMPERE CORRISPONDE 1 AMPERE?",
        a: ["1000", "100", "10000", "10"],
        correct: 0
    },
    // --- PROPAGAZIONE ---
    {
        q: "QUALE STRATO IONOSFERICO E RESPONSABILE DELLA PROPAGAZIONE NOTTURNA HF?",
        a: ["STRATO F", "STRATO D", "STRATO E", "STRATO C"],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA SWR?",
        a: ["RAPPORTO ONDE STAZIONARIE", "POTENZA DI USCITA", "GUADAGNO ANTENNA", "SENSIBILITA RICEVITORE"],
        correct: 0
    },
    {
        q: "QUALE FREQUENZA FA PARTE DELLA BANDA VHF?",
        a: ["145 MHZ", "7 MHZ", "3.5 MHZ", "28 MHZ"],
        correct: 0
    },
    {
        q: "LA PROPAGAZIONE VIA IONOSFERA SI CHIAMA ANCHE?",
        a: ["ONDA DI SPAZIO", "ONDA DI TERRA", "ONDA DI SUPERFICIE", "ONDA DIRETTA"],
        correct: 0
    },
    {
        q: "QUALE CICLO SOLARE DURA CIRCA 11 ANNI?",
        a: ["CICLO DELLE MACCHIE SOLARI", "CICLO LUNARE", "CICLO DELLE MAREE", "CICLO DI IONIZZAZIONE"],
        correct: 0
    },
    {
        q: "COSA SUCCEDE ALL ONDA RADIO SE LA FREQUENZA E SOPRA LA MUF?",
        a: ["L ONDA ATTRAVERSA LA IONOSFERA", "L ONDA VIENE RIFLESSA", "L ONDA VIENE ASSORBITA", "L ONDA RADDOPPIA"],
        correct: 0
    },
    {
        q: "QUAL E L ANTENNA PIU SEMPLICE E USATA DAI RADIOAMATORI?",
        a: ["DIPOLO", "YAGI", "VERTICALE", "QUAD"],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA IL TERMINE DX?",
        a: ["COLLEGAMENTO A LUNGA DISTANZA", "COLLEGAMENTO LOCALE", "BASSA POTENZA", "DIRETTA"],
        correct: 0
    },
    {
        q: "LO STRATO E SPORADICO SI MANIFESTA SOPRATTUTTO IN?",
        a: ["ESTATE", "INVERNO", "AUTUNNO", "NOTTE"],
        correct: 0
    },
    {
        q: "QUALE BANDA HF E NOTA COME BANDA DEI 40 METRI?",
        a: ["7 MHZ", "14 MHZ", "21 MHZ", "3.5 MHZ"],
        correct: 0
    },
    // --- PRATICA OPERATIVA ---
    {
        q: "COSA SIGNIFICA IL CODICE Q QRM?",
        a: ["INTERFERENZA DA ALTRE STAZIONI", "INTERFERENZA ATMOSFERICA", "SEGNALE DEBOLE", "DISTORSIONE AUDIO"],
        correct: 0
    },
    {
        q: "QUALE PREFISSO IDENTIFICA LE STAZIONI ITALIANE?",
        a: ["I", "K", "DL", "EA"],
        correct: 0
    },
    {
        q: "COSA SI USA PER CONFERMARE UN CONTATTO VIA POSTA O DIGITALE?",
        a: ["CARTOLINA QSL", "LOG DI STAZIONE", "DIPLOMA", "RICEVUTA"],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA L ABBREVIAZIONE YL?",
        a: ["GIOVANE SIGNORA", "VECCHIO AMICO", "OPERATORE ESPERTO", "NUOVO SOCIO"],
        correct: 0
    },
    {
        q: "QUALE MODO DIGITALE E MOLTO POPOLARE PER IL DX DEBOLE?",
        a: ["FT8", "CW", "RTTY", "AM"],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA IL CODICE Q QRZ?",
        a: ["CHI MI CHIAMA?", "SONO PRONTO", "CHIUDO LA STAZIONE", "AUMENTATE POTENZA"],
        correct: 0
    },
    {
        q: "QUAL E LA POTENZA MASSIMA PER UN NOMINATIVO ORDINARIO IN ITALIA?",
        a: ["500 WATT", "100 WATT", "1000 WATT", "10 WATT"],
        correct: 0
    },
    {
        q: "IN CW COSA SIGNIFICA L ABBREVIAZIONE SK?",
        a: ["FINE DELLE TRASMISSIONI", "SONO PRONTO", "RIPETETE", "BUONA FORTUNA"],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA IL TERMINE QRP?",
        a: ["BASSA POTENZA", "ALTA POTENZA", "FREQ. LIBERA", "STAZIONE MOBILE"],
        correct: 0
    },
    {
        q: "QUALE TIPO DI CAVO HA IMPEDENZA TIPICA DI 50 OHM?",
        a: ["CAVO COASSIALE", "DOPPINO TELEFONICO", "PIATTINA", "CAVO ELETTRICO"],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA IL CODICE Q QSO?",
        a: ["COLLEGAMENTO RADIO", "NOME DELLA STAZIONE", "ORARIO ESATTO", "METEO"],
        correct: 0
    },
    {
        q: "QUALE BANDA E DEFINITA DEI 20 METRI?",
        a: ["14 MHZ", "7 MHZ", "28 MHZ", "21 MHZ"],
        correct: 0
    },
    {
        q: "COSA MISURA IL RAPPORTO S NEI SEGNALI RADIO?",
        a: ["FORZA DEL SEGNALE", "QUALITA AUDIO", "DISTORSIONE", "LARGHEZZA BANDA"],
        correct: 0
    },
    {
        q: "QUALE COMPONENTE SI USA PER ACCORDARE UN ANTENNA?",
        a: ["ACCORDATORE", "AMPLIFICATORE", "FILTRO", "MODULATORE"],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA L ABBREVIAZIONE WX?",
        a: ["CONDIZIONI METEO", "LAVORO IN CORSO", "STAZIONE REMOTA", "FREQ. OCCUPATA"],
        correct: 0
    },

    // --- CODICE Q E PROCEDURE ---
    {
        q: "COSA SIGNIFICA IL CODICE Q QRN?",
        a: ["DISTURBI ATMOSFERICI ELETTRICI", "INTERFERENZA DA ALTRE STAZIONI", "SEGNALE IN EVANESCENZA", "CAMBIO DI FREQUENZA"],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA IL CODICE Q QSY?",
        a: ["CAMBIO FREQUENZA DI TRASMISSIONE", "CHIUDO LA STAZIONE", "AUMENTO LA POTENZA", "DIMINUISCO LA VELOCITA"],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA IL CODICE Q QSB?",
        a: ["IL SEGNALE E SOGGETTO AD EVANESCENZA (FADING)", "LA TRASMISSIONE E DISTURBATA", "SONO PRONTO A RICEVERE", "INTERROMPO LA TRASMISSIONE"],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA IL CODICE Q QRT?",
        a: ["SOSPENDO LE TRASMISSIONI", "LA MIA POSIZIONE E", "DIMINUITE LA POTENZA", "RIPETETE IL MESSAGGIO"],
        correct: 0
    },
    {
        q: "COSA SIGNIFICA IL CODICE Q QRX?",
        a: ["ATTENDETE, RICHIAMERO", "SONO OCCUPATO", "CONFERMO LA RICEZIONE", "INTERFERENZA ATMOSFERICA"],
        correct: 0
    },
    {
        q: "QUALE PAROLA RAPPRESENTA LA LETTERA A NELL ALFABETO FONETICO INTERNAZIONALE?",
        a: ["ALFA", "AMERICA", "APPLE", "ARIZONA"],
        correct: 0
    },
    {
        q: "QUALE PAROLA RAPPRESENTA LA LETTERA B NELL ALFABETO FONETICO INTERNAZIONALE?",
        a: ["BRAVO", "BOSTON", "BETA", "BAKER"],
        correct: 0
    },
    {
        q: "QUALE PAROLA RAPPRESENTA LA LETTERA R NELL ALFABETO FONETICO INTERNAZIONALE?",
        a: ["ROMEO", "RADIO", "ROGER", "RUSSIA"],
        correct: 0
    },
    {
        q: "COME SI INDICA LA RICEVIBILITA (READABILITY) MASSIMA NEL SISTEMA RST?",
        a: ["5", "9", "10", "3"],
        correct: 0
    },
    {
        q: "COME SI INDICA LA FORZA DEL SEGNALE (STRENGTH) MASSIMA NEL SISTEMA RST?",
        a: ["9", "5", "10", "100"],
        correct: 0
    },
    {
        q: "COSA E UN PILE-UP?",
        a: ["MOLTE STAZIONI CHE CHIAMANO CONTEMPORANEAMENTE LA STESSA STAZIONE", "UN GUASTO ALL ANTENNA", "UN AMPLIFICATORE DI POTENZA LINEARE", "UN DISTURBO SOLARE"],
        correct: 0
    },
    {
        q: "QUALE PREFISSO IDENTIFICA LE STAZIONI RADIOAMATORIALI DELLA SARDEGNA?",
        a: ["IS0", "IT9", "IN3", "IX1"],
        correct: 0
    },
    {
        q: "QUALE PREFISSO IDENTIFICA LE STAZIONI RADIOAMATORIALI DELLA SICILIA?",
        a: ["IT9", "IS0", "IW0", "IK2"],
        correct: 0
    },
    // --- BANDE E FREQUENZE ---
    {
        q: "QUALI SONO I LIMITI DELLA BANDA RADIOAMATORIALE DEI 2 METRI IN ITALIA?",
        a: ["144 - 146 MHZ", "140 - 150 MHZ", "144 - 148 MHZ", "145 - 147 MHZ"],
        correct: 0
    },
    {
        q: "A QUALE BANDA CORRISPONDE LA FREQUENZA DI 50 MHZ?",
        a: ["6 METRI", "10 METRI", "2 METRI", "4 METRI"],
        correct: 0
    },
    {
        q: "A QUALE BANDA CORRISPONDE LA FREQUENZA DI 3.5 MHZ?",
        a: ["80 METRI", "40 METRI", "160 METRI", "20 METRI"],
        correct: 0
    },
    {
        q: "IN QUALE BANDA SI UTILIZZA PREVALENTEMENTE LA MODULAZIONE LSB (LOWER SIDE BAND)?",
        a: ["40 E 80 METRI", "10 E 15 METRI", "2 METRI E 70 CENTIMETRI", "SOLO IN VHF E SUPERIORI"],
        correct: 0
    },
    {
        q: "IN QUALE BANDA SI UTILIZZA PREVALENTEMENTE LA MODULAZIONE USB (UPPER SIDE BAND)?",
        a: ["20, 15 E 10 METRI", "160 E 80 METRI", "ONDE MEDIE", "ONDE LUNGHE"],
        correct: 0
    },
    // --- ELETTROTECNICA E COMPONENTI ---
    {
        q: "SE COLLEGHIAMO DUE RESISTENZE DA 50 OHM IN SERIE, QUAL E LA RESISTENZA TOTALE?",
        a: ["100 OHM", "25 OHM", "50 OHM", "0 OHM"],
        correct: 0
    },
    {
        q: "SE COLLEGHIAMO DUE RESISTENZE DA 50 OHM IN PARALLELO, QUAL E LA RESISTENZA TOTALE?",
        a: ["25 OHM", "100 OHM", "50 OHM", "0 OHM"],
        correct: 0
    },
    {
        q: "COME SI CALCOLA LA POTENZA ELETTRICA (P) IN CORRENTE CONTINUA?",
        a: ["P = V x I", "P = V / I", "P = I / V", "P = V + I"],
        correct: 0
    },
    {
        q: "COSA ESPRIME LA LEGGE DI JOULE?",
        a: ["LA QUANTITA DI CALORE DISSIPATA DA UN CONDUTTORE PERCORSO DA CORRENTE", "LA FORZA DI ATTRAZIONE TRA DUE CARICHE", "L INDUZIONE ELETTROMAGNETICA IN UNA BOBINA", "LA VELOCITA DELLA LUCE NEL VUOTO"],
        correct: 0
    },
    {
        q: "COSA MISURA L AMPEROMETRO E COME VA COLLEGATO?",
        a: ["MISURA LA CORRENTE E VA COLLEGATO IN SERIE AL CIRCUITO", "MISURA LA TENSIONE E VA COLLEGATO IN PARALLELO", "MISURA LA RESISTENZA E VA COLLEGATO IN PARALLELO", "MISURA LA POTENZA E VA COLLEGATO IN SERIE"],
        correct: 0
    },
    {
        q: "COSA MISURA IL VOLTMETRO E COME VA COLLEGATO?",
        a: ["MISURA LA TENSIONE E VA COLLEGATO IN PARALLELO AL CIRCUITO", "MISURA LA CORRENTE E VA COLLEGATO IN SERIE", "MISURA LA RESISTENZA E VA COLLEGATO IN SERIE", "MISURA L INDUTTANZA E VA COLLEGATO IN PARALLELO"],
        correct: 0
    },
    {
        q: "QUAL E L UNITA DI MISURA DELL INDUTTANZA?",
        a: ["HENRY", "FARAD", "OHM", "WATT"],
        correct: 0
    },
    {
        q: "COSA FA UN TRASFORMATORE?",
        a: ["ALZA O ABBASSA LA TENSIONE IN CORRENTE ALTERNATA", "CONVERTE LA CORRENTE ALTERNATA IN CONTINUA", "ACCUMULA ENERGIA SOTTO FORMA DI CAMPO ELETTRICO", "BLOCCA LE BASSE FREQUENZE"],
        correct: 0
    },
    {
        q: "QUALE COMPONENTE ELETTRONICO E UTILIZZATO COME RADDRIZZATORE DI CORRENTE?",
        a: ["DIODO", "CONDENSATORE", "INDUTTORE", "RESISTORE"],
        correct: 0
    },
    {
        q: "A COSA SERVE UN DIODO ZENER?",
        a: ["A MANTENERE COSTANTE LA TENSIONE AI SUOI CAPI", "AD AMPLIFICARE UN SEGNALE RF", "A RICEVERE ONDE RADIO", "A GENERARE SEGNALI IN CW"],
        correct: 0
    },
    {
        q: "COSA SI INTENDE PER MATERIALE ISOLANTE?",
        a: ["UN MATERIALE CHE IMPEDISCE IL PASSAGGIO DELLA CORRENTE ELETTRICA", "UN MATERIALE CHE FACILITA IL PASSAGGIO DI CORRENTE", "UN MATERIALE USATO SOLO PER LE ANTENNE", "UN MATERIALE CON RESISTENZA PARI A ZERO"],
        correct: 0
    },
    // --- RADIOTECNICA ---
    {
        q: "COSA SONO LE ONDE ELETTROMAGNETICHE?",
        a: ["OSCILLAZIONI COMBINATE DI CAMPI ELETTRICI E MAGNETICI", "OSCILLAZIONI DI SOLA CORRENTE CONTINUA", "ONDE SONORE AD ALTA FREQUENZA", "ONDE MECCANICHE NEL VUOTO"],
        correct: 0
    },
    {
        q: "QUAL E LA VELOCITA DELLE ONDE RADIO NEL VUOTO?",
        a: ["CIRCA 300.000 KM AL SECONDO", "CIRCA 340 METRI AL SECONDO", "CIRCA 100.000 KM AL SECONDO", "CIRCA 3.000 KM ALLA LUNARE"],
        correct: 0
    },
    {
        q: "COME SI CALCOLA LA LUNGHEZZA D ONDA (IN METRI) CONOSCENDO LA FREQUENZA (IN MHZ)?",
        a: ["300 DIVISO LA FREQUENZA", "FREQUENZA DIVISO 300", "FREQUENZA MOLTIPLICATA PER 300", "300 PIU LA FREQUENZA"],
        correct: 0
    },
    {
        q: "QUALE E LA FUNZIONE DELLA FREQUENZA INTERMEDIA (IF) IN UN RICEVITORE SUPERETERODINA?",
        a: ["AMPLIFICARE E FILTRARE IL SEGNALE A UNA FREQUENZA FISSA", "RICEVERE IL SEGNALE DALL ANTENNA", "MODULARE LA VOCE IN TRASMISSIONE", "ALIMENTARE L ALTOPARLANTE"],
        correct: 0
    },
    {
        q: "COSA FA IL CIRCUITO AGC (AUTOMATIC GAIN CONTROL) IN UN RICEVITORE?",
        a: ["MANTIENE COSTANTE IL LIVELLO AUDIO AL VARIARE DELL INTENSITA DEL SEGNALE", "EVITA LA SOVRAMODULAZIONE IN TRASMISSIONE", "ELIMINA I DISTURBI IMPULSIVI", "CAMBIA AUTOMATICAMENTE LA FREQUENZA"],
        correct: 0
    },
    {
        q: "COSA FA IL CIRCUITO SQUELCH IN UN RICEVITORE?",
        a: ["SILENZIA L AUDIO QUANDO NON E PRESENTE ALCUN SEGNALE", "SINTONIZZA AUTOMATICAMENTE LE STAZIONI", "RIDUCE LA POTENZA DI TRASMISSIONE", "AMPLIFICA I SEGNALI DEBOLI"],
        correct: 0
    },
    {
        q: "COSA E IL RIT (RECEIVER INCREMENTAL TUNING)?",
        a: ["SPOSTA LA FREQUENZA DI RICEZIONE SENZA ALTERARE QUELLA DI TRASMISSIONE", "UN FILTRO AUDIO PER LA VOCE", "UN SISTEMA DI RAFFREDDAMENTO", "UN MODO DIGITALE"],
        correct: 0
    },
    {
        q: "QUALE MODULAZIONE E PIU EFFICIENTE PER I COLLEGAMENTI DX A LUNGA DISTANZA IN FONIA?",
        a: ["SSB (SINGLE SIDE BAND)", "AM (AMPLITUDE MODULATION)", "FM (FREQUENCY MODULATION)", "DSB (DOUBLE SIDE BAND)"],
        correct: 0
    },
    {
        q: "NELLA MODULAZIONE FM (FREQUENCY MODULATION), COSA VARIA AL VARIARE DEL SEGNALE AUDIO?",
        a: ["LA FREQUENZA DELL ONDA PORTANTE", "L AMPIEZZA DELL ONDA PORTANTE", "LA FASE DELL ONDA PORTANTE", "LA POTENZA DELLA TRASMISSIONE"],
        correct: 0
    },
    {
        q: "QUAL E IL VANTAGGIO DELLA MODULAZIONE SSB RISPETTO ALLA AM?",
        a: ["OCCUPA MENO LARGHEZZA DI BANDA ED E PIU EFFICIENTE", "HA UNA MIGLIORE FEDELTA MUSICALE", "RICHIEDE RICEVITORI PIU SEMPLICI", "PUO ESSERE RICEVUTA DA QUALSIASI RADIO FM"],
        correct: 0
    },
    // --- ANTENNE E LINEE ---
    {
        q: "COSA E UN BALUN?",
        a: ["UN ADATTATORE DI IMPEDENZA TRA LINEA SBILANCIATA E ANTENNA BILANCIATA", "UN FILTRO PER ELIMINARE I DISTURBI", "UN TIPO DI VALVOLA TERMOIONICA", "UN MICROFONO DA TAVOLO"],
        correct: 0
    },
    {
        q: "COSA MISURA IL ROSMETRO (SWR METER)?",
        a: ["IL RAPPORTO DI ONDE STAZIONARIE", "LA TENSIONE DI ALIMENTAZIONE", "LA FREQUENZA DI TRASMISSIONE", "LA POTENZA DI PICCO DELL AUDIO"],
        correct: 0
    },
    {
        q: "COSA E UN DUMMY LOAD (CARICO FITTIZIO)?",
        a: ["UNA RESISTENZA NON IRRADIANTE PER TESTARE IL TRASMETTITORE", "UN ANTENNA FILARE MOLTO LUNGA", "UN TIPO DI BATTERIA", "UN AMPLIFICATORE DI RICEZIONE"],
        correct: 0
    },
    {
        q: "QUAL E L IMPEDENZA CARATTERISTICA TIPICA DEI CAVI COASSIALI RG-213 E RG-58?",
        a: ["50 OHM", "75 OHM", "300 OHM", "600 OHM"],
        correct: 0
    },
    {
        q: "COSA SONO I FILTRI PASSA-BASSO UTILIZZATI IN USCITA AI TRASMETTITORI?",
        a: ["FILTRI CHE ATTENUANO LE FREQUENZE ARMONICHE SUPERIORI", "FILTRI CHE BLOCCANO LA CORRENTE CONTINUA", "FILTRI CHE AMPLIFICANO LE ONDE CORTE", "FILTRI CHE MIGLIORANO LA MODULAZIONE AUDIO"],
        correct: 0
    },
    {
        q: "CHE TIPO DI DIAGRAMMA DI RADIAZIONE HA UN DIPOLO MEZZA ONDA NELLO SPAZIO LIBERO?",
        a: ["A FORMA DI OTTO (BIDIREZIONALE)", "PERFETTAMENTE SFERICO (OMNIDIREZIONALE)", "UNIDIREZIONALE A FORMA DI SIGARO", "PUNTIFORME"],
        correct: 0
    },
    // --- PROPAGAZIONE ---
    {
        q: "CHE COSA E LA MUF (MAXIMUM USABLE FREQUENCY)?",
        a: ["LA FREQUENZA MASSIMA CHE VIENE RIFLESSA DALLA IONOSFERA IN UN DATO MOMENTO", "LA FREQUENZA MASSIMA AUTORIZZATA AI RADIOAMATORI", "LA FREQUENZA LIMITE DEL RICEVITORE", "LA FREQUENZA DOVE L ANTENNA RISONA"],
        correct: 0
    },
    {
        q: "IN CHE MODO L ATTIVITA SOLARE (MACCHIE SOLARI) INFLUENZA LA PROPAGAZIONE HF?",
        a: ["MAGGIORE ATTIVITA SOLARE MIGLIORA LA RIFLESSIONE IONOSFERICA DELLE ALTE FREQUENZE", "MAGGIORE ATTIVITA IMPEDISCE QUALSIASI COMUNICAZIONE", "NON HA ALCUN EFFETTO SULLE HF", "MIGLIORA SOLO LA PROPAGAZIONE DELLE ONDE LUNGHE"],
        correct: 0
    },
    {
        q: "COSA SI INTENDE PER EFFETTO PELLE NELLE RADIOFREQUENZE?",
        a: ["LA CORRENTE AD ALTA FREQUENZA TENDE A SCORRERE SULLA SUPERFICIE DEL CONDUTTORE", "I CAVI SI SCALDANO E LA GUAINA FONDE", "IL SEGNALE VIENE ASSORBITO DAL CORPO UMANO", "L ANTENNA CAMBIA COLORE"],
        correct: 0
    },
    {
        q: "COSA E LA ZONA DI SILENZIO (SKIP ZONE) NELLA PROPAGAZIONE IONOSFERICA?",
        a: ["LA ZONA TRA LA FINE DELL ONDA DI TERRA E IL PUNTO DI PRIMA RIFLESSIONE", "UN AREA DOVE E VIETATO TRASMETTERE", "UNA BANDA RISERVATA AI MILITARI", "LA FASCIA ORARIA NOTTURNA DOVE NON C E PROPAGAZIONE"],
        correct: 0
    },
    // --- TELEGRAFIA (MORSE) ---
    {
        q: "QUALE CARATTERE MORSE CORRISPONDE ALLA LETTERA S?",
        a: ["...", "---", "-.-", ".-."],
        correct: 0
    },
    {
        q: "QUALE CARATTERE MORSE CORRISPONDE ALLA LETTERA O?",
        a: ["---", "...", "-.-", ".-."],
        correct: 0
    },
    {
        q: "QUALE CARATTERE MORSE CORRISPONDE ALLA LETTERA A?",
        a: [".-", "-.", "..", "--"],
        correct: 0
    },
    {
        q: "IN CW, COSA SIGNIFICA L ABBREVIAZIONE K ALLA FINE DI UNA TRASMISSIONE?",
        a: ["INVITO A TRASMETTERE (PASSO)", "FINE DEL COLLEGAMENTO", "ERRORE DI MANIPOLAZIONE", "RIPETETE IL MESSAGGIO"],
        correct: 0
    }
];
