const QUIZ_QUESTIONS = [
    { q: "QUAL E IL SEGNALE DI SOCCORSO INTERNAZIONALE?", a: ["SOS", "CQD", "MAYDAY", "QRR"], correct: 0 },
    { q: "COSA SIGNIFICA IL CODICE Q QTH?", a: ["LA MIA POSIZIONE E", "IL MIO NOME E", "SONO PRONTO", "CHIUDO LA STAZIONE"], correct: 0 },
    { q: "QUALE ABBREVIAZIONE SI USA PER BUONGIORNO?", a: ["GM", "GA", "GN", "GE"], correct: 0 },
    { q: "COSA SIGNIFICA IL CODICE Q QRS?", a: ["TRASMETTETE PIU PIANO", "AUMENTATE LA VELOCITA", "IL SEGNALE E FORTE", "CAMBIO FREQUENZA"], correct: 0 },
    { q: "QUAL E L ABBREVIAZIONE DI BEST REGARDS?", a: ["73", "88", "DX", "GL"], correct: 0 },
    { q: "COSA SIGNIFICA IL CODICE Q QRV?", a: ["SONO PRONTO", "SONO OCCUPATO", "VADO FUORI ONDA", "RIPETETE IL MESSAGGIO"], correct: 0 },
    { q: "QUALE CARATTERE MORSE CORRISPONDE ALLA LETTERA E?", a: [".", "-", "..", ".-"], correct: 0 },
    { q: "QUALE CARATTERE MORSE CORRISPONDE ALLA LETTERA T?", a: ["-", ".", "--", "-."], correct: 0 },
    { q: "COSA SIGNIFICA L ABBREVIAZIONE OM?", a: ["OLD MAN", "OPERATOR MODE", "ONLY MORSE", "OFFICIAL MEMBER"], correct: 0 },
    { q: "COSA SIGNIFICA IL CODICE Q QSL?", a: ["CONFERMO LA RICEZIONE", "NON RICEVO BENE", "LA MIA FREQUENZA E", "SPOSTATEVI"], correct: 0 }
];
